@startuml Algorithme : Recherche Paire
actor user as user
participant front as front
control server as server
database bdd as bdd
server --> server : vérifie la somme du Brelan du Full
alt si un joueur a une somme plus haute
    server --> bdd : ajoute 150 points pour le joueur gagnant dans la table LobbyUsers
    server --> bdd : ajoute 1 au nombre de win pour le gagnant et 1 pour le nombre de lose des perdants
    server --> front : envoie le résultat au front (gagnant, valeur de la combinaison, valeur des dés)
else si deux joueurs ou plus ont une somme du Brelan du Full identique
    alt si la somme de la Paire du Full est plus haute
        server --> bdd : Ajoute 150 points pour le joueur gagnant dans la table LobbyUsers
        server --> bdd : ajoute 1 au nombre de win pour le gagnant et 1 pour le nombre de lose des perdants
        server --> front : envoie le résultat au front (gagnant, valeur de la combinaison, valeur des dés)
    else si la somme de la Paire du Full des joueurs est identique
        server --> bdd : ajoute 1 au nombre de draw pour les joueurs en égalité et 1 au lose pour les perdants
        server --> front : envoie le résultat au front (égalité, valeur de la combinaison, valeur des dés)
    end
end
@enduml