@startuml Algorithme : Recherche Paire
actor user as user
participant front as front
control server as server
database bdd as bdd

server --> server : vérifie la somme de la paire
alt si un joueur a une somme plus haute
    server --> bdd : ajoute 20 points pour le joueur gagnant dans la table LobbyUsers
    server --> bdd : ajoute 1 au nombre de win pour le gagnant et 1 pour le nombre de lose des perdants
    server --> front : envoie le résultat au front (gagnant, valeur de la combinaison, valeur des dés)
else si deux ou plus ont une somme de la paire identique
    loop vérification de chaque dés suivant pour savoir la valeur la plus forte en retirant la paire dans la liste des dés
        alt si un joueur a un dé plus fort que les autres joueur
            break
                server --> bdd : Ajoute 20 points pour le joueur gagnant dans la table LobbyUsers
                server --> bdd : ajoute 1 au nombre de win pour le gagnant et 1 pour le nombre de lose des perdants
                server --> front : envoie le résultat au front (gagnant, valeur de la combinaison, valeur des dés)
            end
        else sinon on recommence la boucle avec le dé plus fort suivant en retirant les dés les plus forts dans la liste des dés
        end
        else si les joueurs ont les mêmes dés
        server --> bdd : ajoute 1 au nombre de draw pour les joueurs en égalité et 1 au lose pour les perdants
        server --> front : envoie le résultat au front (égalité, valeur de la combinaison, valeur des dés)
    end
end


@enduml